#%RAML 1.0 ResourceType
  item:
    description: Entity representing a <<resourcePathName|!singularize>>
    get:
      description: Get the <<resourcePathName|!singularize>> by its ID
      is:
        [ hasResponse: {typeName: <<resourcePathName|!singularize>>, example: <<exampleItem>>}, hasNotFound: {message: "The <<resourcePathName|!singularize>> not found"}]   
    put:
      description: Update <<resourcePathName|!singularize>> 
      securedBy: [ basicAuth ]
      is:
        [hasBadRequest,unauthorized,hasRequestItem: {typeName:<<resourcePathName|!singularize>>}, 
        hasResponse: {typeName: <<resourcePathName|!singularize>>, example: <<exampleItem>>}, 
        hasNotFound: {message: "The <<resourcePathName|!singularize>> not found"}]
    delete:
      description: Delete <<resourcePathName|!singularize>>  by its ID
      securedBy: [ basicAuth ]
      is:
        [unauthorized,hasBeenDeleted,hasNotFound: {message: "The <<resourcePathName|!singularize>> not found"}]   