#%RAML 1.0
title: Company
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/6179c8a0-9d12-47bd-b3c0-183cf2a3f6b8/ # baseUri: http://comapny.api.com
mediaType: application/json
protocols: [HTTPS]
securitySchemes: 
  basicAuth: !include object-model/securityScheme.raml
  
types:
  subsidiary: !include object-model/subsidiary.raml
  employee: !include object-model/employee.raml
  product: !include object-model/product.raml

traits:
  hasRequestItem:
    body:
      application/json:
        type: |
          <<typeName>>
  
  hasBadRequest:
    responses:
      400:
        body:
          application/json:
            example:
              {"message": Object is not valid.The Fields must be not null}
        
  hasBeenCreated:
    response:
      201:
        body:
          application/json:
            type: |
                <<typeName>>
            example: |
                <<example>>

  hasResponse:
    responses:
      200:
        body:
          application/json:
            type: |
              <<typeName>>
            example: |
              <<example>>

  hasBeenDeleted:
    responses:
      204:

             
  hasNotFound:
    responses:
      404:
        body:
          application/json:
            example: |
              <<message>>
              
resourceTypes:
  collection: !include resources/collectionResource.raml
  item: !include resources/itemResource.raml
  readOnlyCollection: !include resources/readOnlyResource.raml

/subsidiares:
  type:
    collection:
          exampleCollection: !include json-examples/subsidiaries.json
          exampleItem: !include json-examples/subsidiary.json
  /{subsidiaryId}:
    type:
      item:
        exampleItem: !include json-examples/subsidiary.json
    /employees:
      type:
        readOnlyCollection:
                  exampleCollection: !include json-examples/subsidiary-employees.json
    /products:
      description: Get all products that are avilable in a subsidiary
      type:
        readOnlyCollection:
                     exampleCollection: !include json-examples/subsidiary-products.json
/eployees:
  type:
    collection:
      exampleCollection: !include json-examples/employees.json
      exampleItem: !include json-examples/employee-retrieve.json
  /{employeId}:
    type:
      item:
        exampleItem: !include json-examples/employee-retrieve.json
        

/products:
  type:
    collection:
          exampleCollection: !include json-examples/products.json
          exampleItem: !include json-examples/product.json
      
  /{productID}:
    type:
      item:
        exampleItem: !include json-examples/product.json

        
        
