#%RAML 1.0
title: Company
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/6179c8a0-9d12-47bd-b3c0-183cf2a3f6b8/ # baseUri: http://comapny.api.com
mediaType: application/json
protocols: [HTTPS]
securitySchemes: 
  basicAuth: !include securityScheme.raml
  
types:
  subsidiary: !include subsidiary.raml
  employee: !include employee.raml
  product: !include product.raml

traits:
  hasBadRequest:
    responses:
      400:
        body:
          application/json:
            example: {"message": "Ids don not match"}
  hasRequestItem:
    body:
      application/json:
        type: |
          <<typeName>>
        
  hasBeenCreated:
    response:
      201:
        body:
          application/json:
            type: |
                <<typeName>>
            example: |
                <<example>>

  hasResponse:
    responses:
      200:
        body:
          application/json:
            type: |
              <<typeName>>
            example: |
              <<example>>

  hasBeenDeleted:
    responses:
      204:
        body:
          application/json:
              example: |
                {message: "The <<resourcePathName|!singularize>> was deleted"}
             
  hasNotFound:
    responses:
      404:
        body:
          application/json:
            example: |
              <<message>>
              
resourceTypes:
  collection: !include collectionResource.raml
  item: !include itemResource.raml
  readOnlyCollection: !include readOnlyResource.raml

/subsidiares:
  type:
    collection:
          exampleCollection: !include subsidiaries.sample
          exampleItem: !include subsidiary.sample
  /{subsidiaryId}:
    type:
      item:
        exampleItem: !include subsidiary.sample
    /employees:
      type:
        readOnlyCollection:
                  exampleCollection: !include subsidiary-employees.sample
    /products:
      description: Get all products that are avilable in a subsidiary
      type:
        readOnlyCollection:
                     exampleCollection: !include subsidiary-products.sample
/eployees:
  type:
    collection:
      exampleCollection: !include employees.sample
      exampleItem: !include employee-retrieve.sample
  /{employeId}:
    type:
      item:
        exampleItem: !include employee-retrieve.sample
        

/products:
  type:
    collection:
          exampleCollection: !include products.sample
          exampleItem: !include product.sample
      
  /{productID}:
    type:
      item:
        exampleItem: !include product.sample

        
        
